- hosts: all
  user: root
  tasks:
    - name: disable service all
      service:
        name: '{{ item }}'
        enabled: no
      with_items:
          - kubelet
          - docker
          - crio
          - containerd
          - kube-proxy
          - kube-scheduler
          - kube-controller-manager
          - kube-apiserver
          - etcd
      ignore_errors: True
    - name: Reboot system
      reboot:
        reboot_timeout: 3600
    - name: Remove file (delete file)
      file:
        path: "/lib/systemd/system/{{ item }}"
        state: absent
      with_items:
          - kubelet.service
          - docker.service
          - crio.service
          - containerd.service
          - kube-proxy.service
          - kube-scheduler.service
          - kube-controller-manager.service
          - kube-apiserver.service
          - etcd.service
          - docker.socket
      ignore_errors: True
    - name: Remove file (delete file)
      file:
        path: "/usr/bin/{{ item }}"
        state: absent
      with_items:
          - crictl
          - docker
          - docker
          - docker-init
          - docker-proxy
          - containerd-shim
          - runc
          - ctr
          - containerd
      ignore_errors: True
    - name: Remove file (delete file)
      file:
        path: "/etc/{{ item }}"
        state: absent
      with_items:
          - crictl.yaml
          - containers
          - containerd
          - docker
          - cni
      ignore_errors: True
    - name: Remove file (delete file)
      file:
        path: "/apps/{{ item }}"
        state: absent
      with_items:
          - etcd
          - k8s
          - work
          - docker
          - cni
          - crio
          - containerd          
      ignore_errors: True
