---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp.storage.unprivileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
    - "*"   
  readOnlyRootFilesystem: false
  # Users and groups
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  # SELinux
  seLinux:
    # SELinux is unused in CaaSP
    rule: 'RunAsAny'