apiVersion: v1
kind: ServiceAccount
metadata:
  name: nettools
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp.nettools.unprivileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: true
  volumes:
    - secret
  readOnlyRootFilesystem: true
  # Users and groups
  runAsUser:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  # SELinux
  seLinux:
    # SELinux is unused in CaaSP
    rule: 'RunAsAny'
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nettools
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames: ['psp.nettools.unprivileged']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nettools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nettools
subjects:
  - kind: ServiceAccount
    name: nettools
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: net-tools
  labels:
    k8s-app: net-tools
spec:
  selector:
    matchLabels:
      k8s-app: net-tools
  template:
    metadata:
      labels:
        k8s-app: net-tools
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccount: nettools
      containers:
      - name: net-tools
        image: juestnow/net-tools
        command:
          - /bin/sh
          - '-c'
          - set -e -x; tail -f /dev/null
        resources:
          limits:
            memory: 30Mi
          requests:
            cpu: 50m
            memory: 20Mi
      dnsConfig:
        options:
          - name: single-request-reopen
