apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"   # true|false
  name: nfs-storage
  namespace: clusterstorage
provisioner: fuseim.pri/ifs
reclaimPolicy: Retain
mountOptions:
  - vers=4.0
  - noresvport
