---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: clusterstorage
stringData:
  # Key values correspond to a user name and its key, as defined in the
  # ceph cluster. User ID should have required access to the 'pool'
  # specified in the storage class
  # ceph auth add client.kube mon 'allow r' osd 'allow rwx pool=kube'
  userID: kube
  userKey: AQApbtJd+5MpMxAApoLnIKuN74Cc3bJUgr7Xyg==

  # Encryption passphrase
  encryptionPassphrase: kube_passphrase
