apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus-adapter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/scheme: 'https'
  name: prometheus-adapter
  namespace: monitoring
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    name: prometheus-adapter
