---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp.prometheus-adapter.unprivileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL  
  volumes:
    - secret
    - emptyDir
    - configMap
  hostNetwork: false
  hostIPC: false
  hostPID: false
  readOnlyRootFilesystem: true
  # Users and groups
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  # SELinux
  seLinux:
    # SELinux is unused in CaaSP
    rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-adapter
rules:
- apiGroups: 
  - policy
  resources: 
  - podsecuritypolicies
  verbs: 
  - use
  resourceNames: 
  - psp.prometheus-adapter.unprivileged
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
  - watch
