apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kubelet
  name: kubelet
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
  selector:
    app: node-exporter # node-exporter  服务名

