apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: node-rules
  namespace: monitoring
spec:
  groups:
    - name: linux Disk Alerts
      rules:
        - alert: DiskSpaceUsage
          expr: 100 - (node_filesystem_free_bytes{fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"} * 100) > 90
          for: 1m
          labels:
            status: high
          annotations:
            summary: "{{$labels.mountpoint}} Partition utilization too high"
            description: "{{$labels.mountpoint }} Partition usage greater than 90%(Currently used:{{$value}}%)"
        - alert: DiskSIOPerformance
          expr: 100-(avg(irate(node_disk_io_time_seconds_total[1m])) by(instance)* 100) < 60
          for: 1m
          labels:
            status: high
          annotations:
            summary: "{{$labels.mountpoint}} The IO utilization rate of incoming disk is too high"
            description: "{{$labels.mountpoint }} The incoming disk IO is greater than 60%(Currently used:{{$value}})"
    - name: linux Cpu
      rules:
        - alert: CpuUsage
          expr: 100-(avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by(instance)* 100) > 60
          for: 1m
          labels:
            status: warning
          annotations:
            summary: "{{$labels.mountpoint}} CPU The utilization rate is too high"
            description: "{{$labels.mountpoint }} CPU Use greater than 60%(Currently used:{{$value}}%)"
    - name: linux Memory
      rules:
        - alert:  MemoryLow
          expr: 100 - (node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100 < 10
          for: 1m
          labels:
            status: high
          annotations:
            summary: "{{$labels.mountpoint}} High memory usage"
            description: "{{$labels.mountpoint }} Memory remaining 10%(Currently used:{{$value}}%)"
    - name: InstanceDown
      rules:
        - alert: InstanceDown
          expr: up == 0
          for: 2m
          labels:
            severity: page
          annotations:
            summary: "Instance {{ $labels.instance }} down"
            description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minute."