apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: redis-rules
  namespace: monitoring
spec:
  groups:
  - name: redis.rules
    rules:
    - alert: RedisLastCreateRdbFailed                       
      expr: redis_rdb_last_bgsave_status != 1
      for: 1m
      labels:
        severity: warning
      annotations:
        description: " Instance {{ $labels.instance }} rdb_last_bgsave_status  "
        summary: "last create rdb failed"
    - alert: NodeCPUIOWAIT
      expr: (irate(node_cpu_seconds_total{job="kubernetes-endpoints",mode="iowait"}[5m])) * 100 > 25
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "{{$labels.instance}}: High CPU IO WAIT usage detected"
        description: "{{$labels.instance}}: CPU IO WAIT is above 25% (current value is: {{ $value }})"
    - alert: NodeDiskUseage
      expr: (node_filesystem_free_bytes{device="/dev/vdb",fstype="xfs",job="kubernetes-endpoints"}) / (node_filesystem_size_bytes) * 100 < 20
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "{{$labels.instance}}: Node free Disk less than 20%"
        description: "{{$labels.instance}}: Node Disk free less than 20% (current value is: {{ $value }})"
    - alert: NodeCPUUsage
      expr: (100 - (irate(node_cpu_seconds_total{job="kubernetes-endpoints",mode="idle"}[5m])) * 100) > 75
      for: 2m
      labels:
        severity: page
      annotations:
        summary: "{{$labels.instance}}: High CPU usage detected"
        description: "{{$labels.instance}}: CPU usage is above 75% (current value is: {{ $value }})"
    - alert: NodeMemoryUsage
      expr: (1-(node_memory_MemAvailable_bytes{job="kubernetes-endpoints"}/ (node_memory_MemTotal_bytes{job="kubernetes-endpoints"})))* 100 > 75
      for: 2m
      labels:
        severity: page
      annotations:
        summary: "{{$labels.instance}}: High memory usage detected"
        description: "{{$labels.instance}}: Memory usage is above 75% (current value is: {{ $value }})"
        ###
    - alert: RedisTooManyClients
      expr: redis_connected_clients > 2000
      for: 5m
      labels:
        severity: warning
      annotations:
        description: "Instance {{ $labels.instance }} Redis linked clients too many, VALUE = {{ $value }}"
        summary: "Redis linked clients too many. This requires immediate action!"
    - alert: RedisMasterLinkFailed                                     
      expr: redis_master_link_up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        description: "Instance {{ $labels.instance }} link failed"
        summary: "redis_master_link=0 link failed"
    - alert: RedisLastAOFFailed
      expr: redis_aof_last_bgrewrite_status != 1
      for: 1m
      labels:
        severity: warning
      annotations:
        description: "Instance {{ $labels.instance }} redis aof last rewrite duration sec"
        summary: "last AOF failed"
    ####
    - alert: Redisdown
      expr: redis_up  == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Redis down (instance {{ $labels.instance }})"
        description: "Redis is down,  VALUE = {{ $value }}  LABELS: {{ $labels }}"                    
    - alert: RedisMemoryOut
      expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Out of memory (instance {{ $labels.instance }})"
        description: "Redis is running out of memory (> 80%)  VALUE = {{ $value }}  LABELS: {{ $labels }}"                             
    - alert: RedisRejectedConnections
      expr: increase(redis_rejected_connections_total[1m]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Rejected connections (instance {{ $labels.instance }})"
        description: "Some connections to Redis has been rejected  VALUE = {{ $value }}  LABELS: {{ $labels }}"